create schema if NOT EXISTS demo;

USE demo;

DROP TABLE IF EXISTS demo.blog;
DROP SEQUENCE IF EXISTS HIBERNATE_SEQUENCE;

CREATE TABLE IF NOT EXISTS demo.blog (
    id bigint(20) NOT NULL AUTO_INCREMENT,
    title VARCHAR(500) NOT NULL,
    content VARCHAR(10000) NOT NULL,
    PRIMARY KEY (id)
);

CREATE SEQUENCE IF NOT EXISTS HIBERNATE_SEQUENCE START WITH 11 INCREMENT BY 1;
